### ISSUE TITLE
ErPredictor not working

### ISSUE THREAD

**Issue by YaserJaradeh** [AskNowQA/EARL#12]
Hi, I am working to include EARL in the AskNow system for German lanaguage, we managed to dockerize it, but then running it i am getting a nasty error, if you can point out what is the issue it would be great.
``` python
/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
2018-03-22 15:41:15.532710: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
[2018-03-23 14:42:43,551] ERROR in app: Exception on /processQuery [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app//EARL/scripts/api.py", line 76, in processQuery
    erpredictions = e.erPredict(chunks)
  File "/app/EARL/scripts/ErPredictor.py", line 62, in erPredict
    chunkwords = chunk[0].translate(None, string.punctuation)
TypeError: translate() takes exactly one argument (2 given)
::ffff:129.26.77.49 - - [2018-03-23 14:42:43] "POST /processQuery HTTP/1.1" 500 412 0.011473
[2018-03-23 14:48:27,905] ERROR in app: Exception on /processQuery [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app//EARL/scripts/api.py", line 76, in processQuery
    erpredictions = e.erPredict(chunks)
  File "/app/EARL/scripts/ErPredictor.py", line 62, in erPredict
    chunkwords = chunk[0].translate(None, string.punctuation)
TypeError: translate() takes exactly one argument (2 given)
::ffff:129.26.77.49 - - [2018-03-23 14:48:27] "POST /processQuery HTTP/1.1" 500 412 0.008723
```

**Comment by debayan** [comment]
I suspect this is an issue of unicode handling. https://stackoverflow.com/questions/23175809/str-translate-gives-typeerror-translate-takes-one-argument-2-given-worked-i

Can you pass me a sample input to this file that makes the code break?  (Last line of this file allows you to specify an input)
